version: '3.9'

services:
  db:
    image: postgres:17
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shukla2004@
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: inventory_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"